USE [master]
GO

/****** Object:  Database [Forca]    Script Date: 03/02/2018 06:48:43 ******/
CREATE DATABASE [Forca]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Forca', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Forca.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Forca_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Forca_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Forca] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Forca].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Forca] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Forca] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Forca] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Forca] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Forca] SET ARITHABORT OFF 
GO

ALTER DATABASE [Forca] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Forca] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Forca] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Forca] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Forca] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Forca] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Forca] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Forca] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Forca] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Forca] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Forca] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Forca] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Forca] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Forca] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Forca] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Forca] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Forca] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Forca] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Forca] SET  MULTI_USER 
GO

ALTER DATABASE [Forca] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Forca] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Forca] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Forca] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Forca] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Forca] SET QUERY_STORE = OFF
GO

USE [Forca]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Forca] SET  READ_WRITE 
GO


